// packages/react/src/ui/wallet-connect-modal/wallet-connect-modal.tsx
import * as React from "react";
import { forwardRef } from "react";
import Button from "../button";
import { WalletConnectModalProps } from "./wallet-connect-modal.types";
import Modal from "../modal";

const WalletConnectModal = forwardRef<WalletConnectModalProps["forwardedRef"]>(
  function WalletConnectModal(props: WalletConnectModalProps, forwardedRef) {
    return (
      <Modal ref={forwardedRef}>
        {props.children}

        <Button>hello</Button>
      </Modal>
    );
  }
);

export default WalletConnectModal;

// packages/vue/src/ui/wallet-connect-modal/wallet-connect-modal.vue
<template>
  <scaffold-modal :trigger="<button>hello</button>">
    <slot />
  </scaffold-modal>
</template>

<script lang="ts">
import Button from "../button";
import { WalletConnectModalProps } from "./wallet-connect-modal.types";

export default {
  name: "wallet-connect-modal",
  components: { ScaffoldModal: ScaffoldModal },
  props: [],
};
</script>
